### ISSUE TITLE
use ctx.app instead

### ISSUE THREAD

**Issue by nswbmw** [yorkie/node-kmongo#1]
koa has ctx.app, there's no need to pass `app`, right? : ]

**Comment by yorkie** [comment]
nope, because we just access `ctx.app` in the function returned by `kmongo()`, but see the following quote:

``` js
co(function * () {
  try {
    mongo = yield createConnection(host, port, args.options);
    args.app.emit('ready');
  } catch (err) {
    args.app.emit('error', err);
  }
})();
```

it creates the connection(pool) to mongod/mongos, and delegates the `ready` event that requires `app`, that moment we could not access `ctx` and `ctx.app`.

@nswbmw, if any wrong of my comment(bcuz i'm busy on my other project), plz let me know and show me related code(pr welcome).

**Comment by yorkie** [comment]
@nswbmw, i have added you as the collaborator of this project.

**Comment by nswbmw** [comment]
how about

```
  return function* (next) {
    var self = this;

    try {
      mongo = yield createConnection(host, port, options);
      self.app.emit('ready');
    } catch (err) {
      self.app.emit('error', err);
    }

    if (!mongo) throw new Error('mongo init required');
    this[name || 'mongo'] = mongo;
    yield next;
  };
```

and

```
app.once('ready', function() {
  console.log("start")
});
app.listen(3000);
```

**Comment by yorkie** [comment]
nope, that means you create connection everytime, this op just is a pre-ready......

**Comment by yorkie** [comment]
what's your mean purpose on this issue?
Maybe we just let the third argument(app) be optional, if you pass app, then:

``` js
app.use(kmongo(opt, app));
app.on('ready', function() {
  // connection pool created
});
```

otherwise, then you just do:

``` js
app.use(kmongo(opt));
app.on('error', function(err) {
  if (err && err.name == 'mongo init required') {
    // connection had not been created
  }
});
```

if this is good to you and you are free to do, may i ask you to create a pr for this, i will update the version and npm package, thanks...

**Comment by yorkie** [comment]
Okay, now you just feel free to construct your params for `kmongo` function like: `kmongo('mongo')`.

**Comment by nswbmw** [comment]
: ]
